# setup environment
dist: bionic
language: java

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-groovy"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

matrix:
  include:
  - os: linux
    jdk: openjdk11
  - os: linux
    jdk: openjdk11
    env: ATOM_CHANNEL=beta

# execute tests; utilizes public jenkinsci server
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
